# Generated by Django 5.2.1 on 2025-05-24 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferremas_back", "0003_carrito_itemcarrito"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcarrito",
            name="carrito",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="ferremas_back.carrito",
            ),
        ),
    ]
