# Generated by Django 5.2.1 on 2025-05-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas_back', '0004_alter_itemcarrito_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='token_ws',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
